export const presets = {
  spotify: {
    title: 'Spotify Premium',
    subtitle: 'Music for everyone',
    promoText: 'Unlimited Music, Anytime Anywhere!',
    primaryColor: '#1DB954',
    secondaryColor: '#121212',
    accentColor: '#1ed760',
    textColor: '#ffffff',
    badge: 'Best Deal',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'Ad-free \u2022 Offline mode \u2022 HD Audio',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '5,000 Ks' },
      { label: '3 Months', price: '12,000 Ks' },
      { label: '6 Months', price: '22,000 Ks' },
    ],
  },
  netflix: {
    title: 'Netflix',
    subtitle: 'Unlimited movies & TV shows',
    promoText: 'Stream Movies & Shows Without Limits!',
    primaryColor: '#E50914',
    secondaryColor: '#141414',
    accentColor: '#b81d24',
    textColor: '#ffffff',
    badge: 'Hot Deal',
    contact: 'Viber - 09xxxxxxxxx',
    features: '4K Ultra HD \u2022 No Ads \u2022 Multi-device',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '8,000 Ks' },
      { label: '3 Months', price: '20,000 Ks' },
      { label: '6 Months', price: '35,000 Ks' },
    ],
  },
  coursera: {
    title: 'Coursera Plus',
    subtitle: 'Learn without limits',
    promoText: 'Invest in Your Future Today!',
    primaryColor: '#0056D2',
    secondaryColor: '#1a1a2e',
    accentColor: '#1c8cf0',
    textColor: '#ffffff',
    badge: 'Limited Offer',
    contact: 'Viber - 09xxxxxxxxx',
    features: '7000+ Courses \u2022 Certificates \u2022 Top Universities',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '10,000 Ks' },
      { label: '3 Months', price: '25,000 Ks' },
      { label: '6 Months', price: '45,000 Ks' },
    ],
  },
  outlineVpn: {
    title: 'Outline VPN',
    subtitle: 'Secure & private browsing',
    promoText: 'Browse Freely, Stay Protected!',
    primaryColor: '#00BFA5',
    secondaryColor: '#1a2332',
    accentColor: '#36efc1',
    textColor: '#ffffff',
    badge: 'Popular',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'No Logs \u2022 Fast Speed \u2022 Unlimited Data',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '3,000 Ks' },
      { label: '3 Months', price: '7,000 Ks' },
      { label: '6 Months', price: '12,000 Ks' },
    ],
  },
  microsoft365: {
    title: 'Microsoft 365',
    subtitle: 'Office apps & cloud storage',
    promoText: 'All Office Apps, One Subscription!',
    primaryColor: '#D83B01',
    secondaryColor: '#1b1b2f',
    accentColor: '#FFB900',
    textColor: '#ffffff',
    badge: 'Best Value',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'Word \u2022 Excel \u2022 PowerPoint \u2022 1TB OneDrive',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '6,000 Ks' },
      { label: '3 Months', price: '15,000 Ks' },
      { label: '6 Months', price: '28,000 Ks' },
    ],
  },
  gemini: {
    title: 'Gemini Pro',
    subtitle: 'Google AI Assistant',
    promoText: 'Supercharge Your Productivity with AI!',
    primaryColor: '#4285F4',
    secondaryColor: '#1a1a2e',
    accentColor: '#34A853',
    textColor: '#ffffff',
    badge: 'New',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'Advanced AI \u2022 1M Context \u2022 Image Generation',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '8,000 Ks' },
      { label: '3 Months', price: '20,000 Ks' },
      { label: '6 Months', price: '35,000 Ks' },
    ],
  },
  chatgpt: {
    title: 'ChatGPT Plus',
    subtitle: 'OpenAI Assistant',
    promoText: 'Smarter AI, Faster Responses!',
    primaryColor: '#10A37F',
    secondaryColor: '#1a1a2a',
    accentColor: '#1ae0a0',
    textColor: '#ffffff',
    badge: 'Trending',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'GPT-4o \u2022 Image Gen \u2022 Priority Access',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '10,000 Ks' },
      { label: '3 Months', price: '25,000 Ks' },
      { label: '6 Months', price: '45,000 Ks' },
    ],
  },
  duolingo: {
    title: 'Duolingo Plus',
    subtitle: 'Learn languages for free',
    promoText: 'Master Any Language, Your Way!',
    primaryColor: '#58CC02',
    secondaryColor: '#1a1a24',
    accentColor: '#89e219',
    textColor: '#ffffff',
    badge: 'Popular',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'No Ads \u2022 Offline \u2022 Unlimited Hearts',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '5,000 Ks' },
      { label: '3 Months', price: '12,000 Ks' },
      { label: '6 Months', price: '20,000 Ks' },
    ],
  },
  expressVpn: {
    title: 'ExpressVPN',
    subtitle: 'Fast & secure VPN',
    promoText: 'Blazing Fast, Fully Encrypted!',
    primaryColor: '#DA3940',
    secondaryColor: '#1a1a28',
    accentColor: '#ff6b6b',
    textColor: '#ffffff',
    badge: 'Top Rated',
    contact: 'Viber - 09xxxxxxxxx',
    features: '105 Countries \u2022 No Logs \u2022 Unlimited Speed',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '5,000 Ks' },
      { label: '3 Months', price: '12,000 Ks' },
      { label: '6 Months', price: '20,000 Ks' },
    ],
  },
  telegram: {
    title: 'Telegram Premium',
    subtitle: 'Messaging reimagined',
    promoText: 'Unlock Exclusive Features!',
    primaryColor: '#2AABEE',
    secondaryColor: '#1a1a2e',
    accentColor: '#6bd3ff',
    textColor: '#ffffff',
    badge: 'Exclusive',
    contact: 'Viber - 09xxxxxxxxx',
    features: '4GB Upload \u2022 No Ads \u2022 Premium Stickers',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '4,000 Ks' },
      { label: '3 Months', price: '10,000 Ks' },
      { label: '6 Months', price: '18,000 Ks' },
    ],
  },
  youtube: {
    title: 'YouTube Premium',
    subtitle: 'Watch without interruptions',
    promoText: 'Ad-Free Videos, Anytime!',
    primaryColor: '#FF0000',
    secondaryColor: '#181818',
    accentColor: '#ff4e4e',
    textColor: '#ffffff',
    badge: 'Hot Deal',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'No Ads \u2022 Background Play \u2022 YouTube Music',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '6,000 Ks' },
      { label: '3 Months', price: '15,000 Ks' },
      { label: '6 Months', price: '26,000 Ks' },
    ],
  },
  appleMusic: {
    title: 'Apple Music',
    subtitle: 'Over 100 million songs',
    promoText: 'Lossless Audio, Spatial Sound!',
    primaryColor: '#FC3C44',
    secondaryColor: '#1a1a2e',
    accentColor: '#fa7096',
    textColor: '#ffffff',
    badge: 'Premium',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'Lossless \u2022 Spatial Audio \u2022 Lyrics',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '5,000 Ks' },
      { label: '3 Months', price: '12,000 Ks' },
      { label: '6 Months', price: '22,000 Ks' },
    ],
  },
};
