export const presets = {
  spotify: {
    title: 'Spotify Premium',
    subtitle: 'Music for everyone',
    promoText: 'Unlimited Music, Anytime Anywhere!',
    primaryColor: '#1DB954',
    secondaryColor: '#121212',
    accentColor: '#1ed760',
    textColor: '#ffffff',
    badge: 'Best Deal',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'Ad-free \u2022 Offline mode \u2022 HD Audio',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '5,000 Ks' },
      { label: '3 Months', price: '12,000 Ks' },
      { label: '6 Months', price: '22,000 Ks' },
    ],
  },
  netflix: {
    title: 'Netflix',
    subtitle: 'Unlimited movies & TV shows',
    promoText: 'Stream Movies & Shows Without Limits!',
    primaryColor: '#E50914',
    secondaryColor: '#141414',
    accentColor: '#b81d24',
    textColor: '#ffffff',
    badge: 'Hot Deal',
    contact: 'Viber - 09xxxxxxxxx',
    features: '4K Ultra HD \u2022 No Ads \u2022 Multi-device',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '8,000 Ks' },
      { label: '3 Months', price: '20,000 Ks' },
      { label: '6 Months', price: '35,000 Ks' },
    ],
  },
  coursera: {
    title: 'Coursera Plus',
    subtitle: 'Learn without limits',
    promoText: 'Invest in Your Future Today!',
    primaryColor: '#0056D2',
    secondaryColor: '#1a1a2e',
    accentColor: '#1c8cf0',
    textColor: '#ffffff',
    badge: 'Limited Offer',
    contact: 'Viber - 09xxxxxxxxx',
    features: '7000+ Courses \u2022 Certificates \u2022 Top Universities',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '10,000 Ks' },
      { label: '3 Months', price: '25,000 Ks' },
      { label: '6 Months', price: '45,000 Ks' },
    ],
  },
  outlineVpn: {
    title: 'Outline VPN',
    subtitle: 'Secure & private browsing',
    promoText: 'Browse Freely, Stay Protected!',
    primaryColor: '#00BFA5',
    secondaryColor: '#1a2332',
    accentColor: '#36efc1',
    textColor: '#ffffff',
    badge: 'Popular',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'No Logs \u2022 Fast Speed \u2022 Unlimited Data',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '3,000 Ks' },
      { label: '3 Months', price: '7,000 Ks' },
      { label: '6 Months', price: '12,000 Ks' },
    ],
  },
  microsoft365: {
    title: 'Microsoft 365',
    subtitle: 'Office apps & cloud storage',
    promoText: 'All Office Apps, One Subscription!',
    primaryColor: '#D83B01',
    secondaryColor: '#1b1b2f',
    accentColor: '#FFB900',
    textColor: '#ffffff',
    badge: 'Best Value',
    contact: 'Viber - 09xxxxxxxxx',
    features: 'Word \u2022 Excel \u2022 PowerPoint \u2022 1TB OneDrive',
    shopName: 'DMar Premium Service',
    plans: [
      { label: '1 Month', price: '6,000 Ks' },
      { label: '3 Months', price: '15,000 Ks' },
      { label: '6 Months', price: '28,000 Ks' },
    ],
  },
};
